### ISSUE TITLE
libgfortran.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TamouzeAssi** [Anaconda-Platform/anaconda-project#150]
hello,

Can you help me  to go out from these error. It was a nightmare when i tried to solve it :grinning: 
```Traceback (most recent call last):
  File "/project/6008168/tamouze/Python_directory/lda2vec/examples/twenty_newsgroups/lda2vec/lda2vec_run.py", line 18, in <module>
    from lda2vec import utils
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/lda2vec/__init__.py", line 3, in <module>
    import tracking
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/lda2vec/tracking.py", line 2, in <module>
    from sklearn.linear_model import LinearRegression
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scikit_learn-0.19.1-py2.7-linux-x86_64.egg/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scikit_learn-0.19.1-py2.7-linux-x86_64.egg/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scikit_learn-0.19.1-py2.7-linux-x86_64.egg/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scikit_learn-0.19.1-py2.7-linux-x86_64.egg/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scikit_learn-0.19.1-py2.7-linux-x86_64.egg/sklearn/utils/fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scipy-1.1.0rc1-py2.7-linux-x86_64.egg/scipy/sparse/linalg/__init__.py", line 114, in <module>
    from .isolve import *
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scipy-1.1.0rc1-py2.7-linux-x86_64.egg/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/home/tamouze/anaconda2/envs/testing-env/lib/python2.7/site-packages/scipy-1.1.0rc1-py2.7-linux-x86_64.egg/scipy/sparse/linalg/isolve/iterative.py", line 10, in <module>
    from . import _iterative
ImportError: libgfortran.so.4: cannot open shared object file: No such file or directory
```

my environment contains:
```
# packages in environment at /home/tamouze/anaconda2/envs/testing-env:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cffi                      1.11.5           py27h9745a5d_0
chainer                   4.0.0                     <pip>
chardet                   3.0.4            py27hfa10054_1
cloudpickle               0.5.2                    py27_1
cryptography              2.2.2            py27h14c3975_0
cudatoolkit               9.0                  h13b8566_0
cudnn                     7.1.2                 cuda9.0_0
cupy                      4.0.0            py27he3f55b6_0
cymem                     1.31.2                   py27_0    spacy
cytoolz                   0.8.2            py27hf14aec9_0
dill                      0.2.7.1          py27h28bf823_0
en-core-web-sm            2.0.0                     <pip>
enum34                    1.1.6            py27h99a27e9_1
fastrlock                 0.3              py27hf484d3e_0
filelock                  3.0.4                    py27_0
ftfy                      4.4.3                    py27_0
html5lib                  1.0.1            py27h5233db4_0
idna                      2.6              py27h5722d68_1
intel-openmp              2018.0.0                      8
ipaddress                 1.0.22                   py27_0
lda2vec                   0.1                       <pip>
libedit                   3.1                  heed3624_0
libffi                    3.2.1                hd88cf55_4
libgcc                    7.2.0                h69d50b8_2
libgcc-ng                 7.2.0                hdf63c60_3
libgfortran-ng            7.2.0                hdf63c60_3
libprotobuf               3.5.2                h6f1eeef_0
libstdcxx-ng              7.2.0                hdf63c60_3
mkl                       2018.0.2                      1
mkl_fft                   1.0.1            py27h3010b51_0
mkl_random                1.0.1            py27h629b387_0
msgpack-numpy             0.4.1            py27h8e01e4a_0
msgpack-python            0.4.8            py27hc2fa789_0
msgpack-python            0.5.6                     <pip>
murmurhash                0.28.0                   py27_0
nccl                      1.3.5                 cuda9.0_0
ncurses                   6.0                  h9df7e31_2
numpy                     1.14.2           py27hdbf6ddf_1
openssl                   1.0.2o                        0    conda-forge
pathlib                   1.0.1                    py27_0
pip                       9.0.3                    py27_0
plac                      0.9.6                    py27_0
preshed                   1.0.0                    py27_0
protobuf                  3.5.2            py27hf484d3e_0
pycparser                 2.18             py27hefa08c5_1
pyopenssl                 17.5.0           py27hcee3be0_0
pysocks                   1.6.8                    py27_0
python                    2.7.14              h1571d57_31
readline                  7.0                  ha6073c6_4
regex                     2017.11.09       py27h2a269fe_0
regex                     2017.4.5                  <pip>
requests                  2.18.4           py27hc5b0589_1
scikit-learn              0.19.1                    <pip>
scipy                     1.1.0rc1                  <pip>
semver                    2.4.1                    py27_0    spacy
setuptools                39.0.1                   py27_0
six                       1.11.0           py27h5f960f1_1
sklearn                   0.0                       <pip>
spacy                     2.0.7                    py27_2    conda-forge
spacy                     2.0.11                    <pip>
sputnik                   0.9.3                    py27_0    spacy
sqlite                    3.23.1               he433501_0
termcolor                 1.1.0                    py27_1
thinc                     6.10.2                   py27_0    conda-forge
tk                        8.6.7                hc745277_3
toolz                     0.9.0                    py27_0
tqdm                      4.23.1                    <pip>
tqdm                      4.23.0                   py27_0
ujson                     1.35                     py27_0
urllib3                   1.22             py27ha55213b_0
wcwidth                   0.1.7            py27h9e3e1ab_0
webencodings              0.5.1            py27hff10b21_1
wheel                     0.31.0                   py27_0
wrapt                     1.10.11          py27h04f6869_0
zlib                      1.2.11               ha838bed_2
```

**Comment by mcg1969** [comment]
I'm afraid this is the wrong issue page. This should likely go to
https://github.com/ContinuumIO/anaconda-issues/issues
