### ISSUE TITLE
Error in importing tensorflow : Anaconda

### ISSUE THREAD

**Issue by isalam1815** [Anaconda-Platform/anaconda-project#187]
**Hi, 
I am getting following error while trying to import tensorflow in anaconda base environment. Can somebody please see to it and give suggestions to fix it? It will be very helpful.**
 
Here is error detail :

import tensorflow

Traceback (most recent call last):
  File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

**During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  
File "C:\Users\isalam\AppData\Local\Continuum\anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
**ImportError: DLL load failed: The specified module could not be found.**

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by mcg1969** [comment]
This is not the correct forum for this issue, I'm afraid. Perhaps you mean to post on https://github.com/ContinuumIO/anaconda-issues ?
