### ISSUE TITLE
 indentationError when trying create virtualenv #188

### ISSUE THREAD

**Issue by Turall** [Anaconda-Platform/anaconda-project#188]
OS: ParrotOS
virtualenv version : 16.4.3

Running virtualenv with interpreter /home/tural/anaconda3/bin/python3
Using base prefix '/home/tural/anaconda3'
New python executable in /home/tural/Documents/.py3/bin/python3
Also creating executable in /home/tural/Documents/.py3/bin/python
Command /home/tural/Documents/.py3/bin/python3 -m pip config list had error code 1
Traceback (most recent call last):
  File "/home/tural/.local/lib/python3.7/site-packages/virtualenv.py", line 2567, in <module>
    main()
  File "/home/tural/.local/lib/python3.7/site-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/home/tural/.local/lib/python3.7/site-packages/virtualenv.py", line 1088, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/home/tural/.local/lib/python3.7/site-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/home/tural/.local/lib/python3.7/site-packages/virtualenv.py", line 964, in _install_wheel_with_search_dir
    config = _pip_config(py_executable, python_path)
  File "/home/tural/.local/lib/python3.7/site-packages/virtualenv.py", line 1043, in _pip_config
    config[key] = ast.literal_eval(value)
  File "/home/tural/anaconda3/lib/python3.7/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/tural/anaconda3/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    threading.local()
    ^
IndentationError: unexpected indent

**Comment by mcg1969** [comment]
This is the wrong forum to post this issue; this is for a specific package called `anaconda-project`.
