### ISSUE TITLE
ImportError: No yaml library available.

### ISSUE THREAD

**Issue by Excentricitet** [Anaconda-Platform/anaconda-project#219]
Linux Mint 18. Maybe it happened after update Anaconda Navigator, but then always returned:
`    Traceback (most recent call last):
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 19, in get_yaml
    import ruamel_yaml as yaml
ModuleNotFoundError: No module named 'ruamel_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 22, in get_yaml
    import ruamel.yaml as yaml
ModuleNotFoundError: No module named 'ruamel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 137, in main
    from ..activate import main as activator_main
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/activate.py", line 23, in <module>
    from .base.context import ROOT_ENV_NAME, context, locate_prefix_by_name
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 28, in <module>
    from ..common.configuration import (Configuration, ConfigurationLoadError, MapParameter,
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 40, in <module>
    from .serialize import yaml_load
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 30, in <module>
    yaml = get_yaml()
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 59, in _memoized_func
    result = func(*args, **kwargs)
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 24, in get_yaml
    raise ImportError("No yaml library available.\n"
ImportError: No yaml library available.
To proceed, conda install ruamel_yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 19, in get_yaml
    import ruamel_yaml as yaml
ModuleNotFoundError: No module named 'ruamel_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 22, in get_yaml
    import ruamel.yaml as yaml
ModuleNotFoundError: No module named 'ruamel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/timur/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 147, in main
    return ExceptionHandler().handle_exception(exc_val, exc_tb)
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1175, in print_unexpected_error_report
    from .base.context import context
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 28, in <module>
    from ..common.configuration import (Configuration, ConfigurationLoadError, MapParameter,
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/configuration.py", line 40, in <module>
    from .serialize import yaml_load
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 30, in <module>
    yaml = get_yaml()
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 59, in _memoized_func
    result = func(*args, **kwargs)
  File "/home/timur/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 24, in get_yaml
    raise ImportError("No yaml library available.\n"
ImportError: No yaml library available.
To proceed, conda install ruamel_yaml`

I tried use `conda install ruamel_yaml`, but conda returns same output. Also it returns same output with `conda list`
Then i used `rm -rf ~/anaconda3` and now i haven't conda command 
`conda: command not found`
Now in my home directory:
![image](https://user-images.githubusercontent.com/43474772/62364587-8ff59100-b52a-11e9-87f5-fb9730486d5b.png)
![image](https://user-images.githubusercontent.com/43474772/62364538-6fc5d200-b52a-11e9-9a5b-97b306e09fb0.png)

.bashrc file:
```
# added by Anaconda3 5.3.1 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/timur/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/timur/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/timur/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/timur/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
export PATH="$PATH:/opt/idea-IU-191.7479.19/bin"
export PATH="$PATH:/usr/bin/java"
export JAVA_HOME=/usr/bin/java
export PATH=~/anaconda3/bin:$PATH
```

How can i repair it?

**Comment by Excentricitet** [comment]
on Windows 10 i also faced issues. But i thought i did smthing wrong  and reason was in xtensor and my steps of mannually uninstalling numpy:
[https://github.com/QuantStack/xtensor/issues/1665](url)
[https://github.com/QuantStack/xtensor/issues/1661](url)
Then cmd also couldn't found command `anaconda-navigator`, `jupyter-notebook`. But i could run Anaconda from Windows menu. But even Navigator didn't show `Spyder` and couln't uninstall jupyter.

**Comment by mcg1969** [comment]
I'm afraid you are posting in the wrong forum. Perhaps you intend this to be for https://github.com/ContinuumIO/anaconda-issues ? This is an issue tracker for a single, specific piece of software.
