### ISSUE TITLE
Anaconda navigator is not loading applications on Manjaro

### ISSUE THREAD

**Issue by tbhaxor** [Anaconda-Platform/anaconda-project#261]
I have installed the anaconda package. While opening the anaconda navigator from `~/anaconda/bin/anaconda-navigator` The startup screen freezes at Loading applications

![](https://forum.manjaro.org/uploads/default/original/3X/b/f/bf7d03fe68f94bb24683f3fe4a2369f3c0480b55.png)

My conda info
```
     active environment : base
    active env location : /home/terabyte/anaconda3
            shell level : 1
       user config file : /home/terabyte/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.31
       base environment : /home/terabyte/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/terabyte/anaconda3/pkgs
                          /home/terabyte/.conda/pkgs
       envs directories : /home/terabyte/anaconda3/envs
                          /home/terabyte/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/5.4.28-1-MANJARO manjaro/19.0.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/terabyte/.netrc
           offline mode : False
```

Console Logs
```
Traceback (most recent call last):
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 541, in setup
    self.post_setup(conda_data=conda_data)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 578, in post_setup
    self.tab_home.setup(conda_data)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/tabs/home.py", line 169, in setup
    self.set_applications(applications, packages)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/tabs/home.py", line 204, in set_applications
    apps = self.api.process_apps(applications, prefix=self.current_prefix)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 848, in process_apps
    app = app(config=self.config, process_api=self._process_api, conda_api=self._conda_api)
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/vscode.py", line 48, in __init__
    **kwargs
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/base.py", line 43, in __init__
    self.init()
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/base.py", line 60, in init
    SUBDIR, INST_EXT, INST_DIR = self._find_linux_install_dir()
  File "/home/terabyte/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/external_apps/vscode.py", line 168, in _find_linux_install_dir
    if DISTRO_NAME in ['ubuntu', 'debian']:
UnboundLocalError: local variable 'DISTRO_NAME' referenced before assignment
```

**Comment by mcg1969** [comment]
I'm afraid this is not the correct issue tracker—this is for issues specifically related to the anaconda-project Python package.
